### GET all audio books
GET localhost:8080/api/v1/audio-book

### POST create new audio book
POST localhost:8080/api/v1/audio-book
Content-Type: application/json

{
  "title": "Test 2",
  "summary": "",
  "releaseDate": "2019-10-11T09:21:04.981Z",
  "ongoing": true,
  "rating": 0,
  "genreIds": []
}

### PUT update audio book
PUT localhost:8080/api/v1/audio-book/445c7da5-0b3a-441c-83cb-b27583afb4f8
Content-Type: application/json

{
  "title": "Test X",
  "summary": "",
  "releaseDate": "2019-10-11T09:21:04.981Z",
  "ongoing": false,
  "rating": 5,
  "genreIds": []
}

###